networks:
  default:

volumes:
  postgres-data:
  redis-data:

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html:delegated
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../src:/var/www/html:delegated
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - /redis-data:/bitnami/redis/data
